name: Automacao da base de dados

on: 
  push:
    branches: [ 'main' ] 
  schedule: 
    - cron: '0 0 * * *'


jobs:
  automacao: 
    runs-on: ubuntu - 22.04

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v4

      - name: Instalar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Instalar Poetry
        uses: snok/install-poetry@v1
        with:
          version: 2.1.3
        
      - name: Instalar pacotes Python
        run: poetry install --no-root

      - name: Instalar Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.32

      - name: Atualizacao de relatorio
        run: |
          poetry config virtualenvs.prefer-active-python true 
          poetry run quarto render Relatorio/relatorio.qmd
        
      - name: Deploy da Dashboard
        run: |
          poetry run dashboard/etl.py
          poetry run rsconnect add --account ${{ secrets.ACCOUNT }} --name ${{ secrets.NAME }} --token ${{ secrets.TOKEN }} --secret ${{ secrets.SECRET }}
          poetry run rsconnect deploy shiny Dashboard --name macro_copa

      - name: Commit & Push
        uses: stefanzweifel/git-auto-commit-action@v6
        with:
          commit_message: Automacao de relatorio e dashboard
     